name: Terraform CI

on:
  pull_request:
    branches: [ main ]
    paths: [ "terraform/**" ]
  push:
    branches: [ main ]
    paths: [ "terraform/**" ]

jobs:
  terraform:
    name: Terraform Validate & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      #  Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      #  Terraform Init
      - name: Terraform Init
        run: terraform init -backend=false

    #   #  Terraform Format Check
    #   - name: Terraform Format
    #     run: terraform fmt -check -recursive

      #  Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Unit Tests
      - name: Terraform Test
        run: terraform test
