name: Terraform Apply PROD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply-prod:
    runs-on: ubuntu-latest
    environment: prod   # manual approval

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-deployer@PROJECT_ID.iam.gserviceaccount.com"

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: terraform/envs/prod

      - run: terraform apply
        working-directory: terraform/envs/prod
